linters:
  QualifyingElement:
    exclude:
      - "site/_sass/_code-highlight.scss"
  SelectorDepth:
    enabled: false
  NestingDepth:
    enabled: false
  LeadingZero:
    enabled: true
    style: 'include_zero'
