# coding: utf-8
task default: %w[serve]

desc "Init"
task :init do
  sh "bundle install"
end

desc "Serve simply"
task :serve do
  sh "bundle exec jekyll serve"
end

desc "Serve with draft"
task :draft do
  sh "bundle exec jekyll serve --draft"
end

desc "Build jekyll and push to gh-pages branch"
task :site do
  # Clone to gh-pages
  unless File.exist?("./gh-pages")
    sh "git clone -b gh-pages https://github.com/crispgm/crispgm.com.git gh-pages"
  end
  # Checkout and pull
  Dir.chdir('gh-pages') do
    sh "git checkout gh-pages"
    sh "git pull origin gh-pages"
  end
  # Build site with Jekyll
  sh "bundle exec jekyll build --destination=gh-pages"
  # Push
  Dir.chdir('gh-pages') do
    sh "git add ."
    sh "git commit --allow-empty -m \"Deployed at #{Time.now}\""
    sh "git push origin gh-pages"
  end
end