# Site settings
title: DAVID ZHANG
author: David Zhang
email: crispgm@gmail.com
description: "Focus on apps, programming, electronic devices, photography and lifestyles. 主要专注于App应用,程序开发,电子设备,摄影和生活方式"
keywords:
  - David Zhang
  - crisp
  - crispgm
  - Crisp Blog
  - Crisp 博客
url: "https://crispgm.com"
encoding: utf-8

# Build settings
markdown: kramdown

collections:
  docs:
    output: true

plugins_dir: _plugins
gems:
  - jemoji
  - jekyll-tagslist

exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
