# Site settings
title: DAVID ZHANG
author: David Zhang
description: "A minimalist programmer, photographer and lifes lover."
url: "https://crispgm.com"
encoding: utf-8
markdown: kramdown

collections:
  docs:
    output: true

plugins_dir: _plugins
gems:
  - jemoji
  - jekyll-tagslist
  - jekyll-disqus
  - jekyll-google-analytics

twitter:
  username: crispgm
disqus:
  username: crispgm
ga:
  tracking_id: UA-50708664-1

exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
