# Site settings
title: DAVID ZHANG
author: David Zhang
email: crispgm@gmail.com
description: "Focus on apps, programming, electronic devices, photography and lifestyles. 主要专注于App应用,程序开发,电子设备,摄影和生活方式"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://crispgm.com" # the base hostname & protocol for your site
encoding: utf-8
twitter_username: crispgm
github_username:  crispgm

# Build settings
markdown: kramdown

collections:
  docs:
    output: true

plugins_dir: _plugins
gems:
    - jemoji
    - jekyll-tagslist
