# coding: utf-8
task default: %w[serve]

desc "Init"
task :init do
  sh "git submodule update --init --recursive"
end

desc "Serve simply"
task :serve do
  sh "cp data/resume.yml resume/_data"
  sh "cp _config.yml resume"
  Dir.chdir('resume') do
    sh "jekyll serve"
  end
end

desc "Build jekyll and push to gh-pages branch"
task :build do
  # Clone to gh-pages
  unless File.exist?("../gh-pages")
    sh "git clone -b gh-pages https://github.com/crispgm/crispgm.com.git ../gh-pages"
  end
  # Checkout and pull
  Dir.chdir('../gh-pages') do
    sh "git checkout gh-pages"
    sh "git pull origin gh-pages"
  end
  # Build site with Jekyll
  Dir.chdir('resume') do
    sh "git stash"
    sh "git pull origin master"
    sh "cp ../data/resume.yml _data"
    sh "cp ../_config.yml ."
    sh "jekyll build --destination=../../gh-pages/resume/"
  end
  # Push
  Dir.chdir('../gh-pages') do
    sh "git add ."
    sh "git commit --allow-empty -m \"Resume: Deployed at #{Time.now}\""
    sh "git push origin gh-pages"
  end
end