name: build
on: [push, pull_request]
jobs:
  ci:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - name: 'Update Rubygems & Bundler'
        run: 'gem update --system --no-document && gem update bundler --no-document'
      - name: 'Install Bundler 2'
        run: 'gem install bundler -v "2.0.1" --force'
      - run: 'bundle install'
      - run: 'bundle exec rake init'
      - run: 'rake test'
      - run: 'bundle exec scss-lint site/_sass'
