name: publish
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 1 1 *"
jobs:
  publish:
    name: run
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[no publish]')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - name: 'Update Rubygems & Bundler'
        run: 'gem update --system --no-document && gem update bundler --no-document'
      - name: 'Install Bundler 2'
        run: 'gem install bundler -v "2.0.1" --force'
      - run: 'bundle install'
      - run: 'bundle exec rake site:build'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
